sudo: false
os:
  - linux
  - osx
language: node_js
before_script:
  - git clone https://github.com/armory3d/armory_ci
  - git clone --recursive https://github.com/kode/Kha.git armory_ci/test1/Kha
  - git clone https://github.com/armory3d/iron.git armory_ci/test1/Libraries/iron
  - git clone https://github.com/kode/nodejs_bin.git armory_ci/test1/nodejs_bin
  - armory_ci/test1/nodejs_bin/copysysbin.sh
script: 
  - cd armory_ci/test1
  - nodejs_bin/node Kha/make.js krom
